name: Publish Scaraflow to PyPI

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # -------------------------
      # Checkout code
      # -------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # -------------------------
      # Setup Python
      # -------------------------
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # -------------------------
      # Install build tools
      # -------------------------
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      # -------------------------
      # Build package
      # -------------------------
      - name: Build package
        run: |
          python -m build

      # -------------------------
      # Publish to PyPI
      # -------------------------
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine upload dist/*
